# fly.toml app configuration file generated for flyio-silent-haze-7043 on 2025-02-10T12:13:49+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'flyio-silent-haze-7043'
primary_region = 'waw'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  min_machines_running = 0
  auto_stop_machines = false
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
[env]
  WEB_CONCURRENCY = "1"
[processes]
  app = "gunicorn -b 0.0.0.0:8080 --timeout 120 --workers 1 main:app"
